---
title: "SRDBV5-ESSD"
output: html_document
---

```{r preliminaries, message=FALSE, echo=FALSE}
package_list <- c("cowplot","data.table","dplyr","ggplot2", "lubridate", "leaflet"        
                  , "kableExtra","knitr","ggmap","maps","mapdata","tidyr","sp","ggpubr"
                  , "styler", "xlsx", "readxl", "RColorBrewer")

package_new <- package_list[!(package_list %in% installed.packages()[,"Package"])]
if(length(package_new)) install.packages(package_new)

# loading necessary packages
# library("xlsx")
library(readxl)
library(styler)
library(ggplot2)
theme_set(theme_bw())
library(cowplot)
library(tidyr)
library(dplyr)
library(cowplot)
library(data.table)
library(lubridate)
library(kableExtra)
library(knitr)
library(ggpubr)
library(ggmap)
library(maps)
library(mapdata)
library(leaflet)
library(sp)
library(drake)
# Source all needed functions
source('functions.R')

# set data and outputs file direction
DATA_DIR <- 'data'
OUT_DIR <- 'outputs'

# Set chunks defaults; these options will be applied to all subsequent chunks
knitr::opts_chunk$set(results = 'hide', message = TRUE, include = TRUE, 
                      echo = FALSE, warning = FALSE,
                      fig.height = 4, fig.width = 8, cache = FALSE)
```

# Load data
```{r load data}
# load all data necessary for this analysis
srdbv1 <- readd(srdbv1)
srdbv2 <- readd(srdbv2)
srdbv3 <- readd(srdbv3)
srdbv4 <- readd(srdbv4)
srdbv5 <- readd(srdbv5)
srdb_citation <- readd(srdb_citation)
srdb_study <- readd(srdb_study)
IGBP <- readd(IGBP)
GlobalMATMAP <- readd(GlobalMATMAP)
```


```{r get barren and koppen}
IGBP %>% count(barren_yn)
IGBP %>% count(ClimateTypes)
IGBP %>% count(Ecosystem)
IGBP %>% count(Ecosystem2)
```

# ESSD-SRDB-V5 manuscript plots
## srdb citation analysis
```{r Figure 1 - citation}
srdb_citation %>% 
  select(PubYear, Num_citation, Database) %>%  
  ggplot(aes(PubYear, fill = Database)) +
  geom_bar(stat = "count") +
  scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  labs(x=expression(Year), y=expression(Count))

# ggsave('outputs/Figure1.srdb_citation.jpg', width = 8, height = 5)
```


```{r Figure 2 - Sites spatial distribution}
# Base map - word map
worldMap <- map_data(map = "world")
basemap <- word_bkgd(worldMap)

# add srdb-v4 sites
# RC sites from SRDB_v4
srdbv4 %>% 
  select(Latitude, Longitude) %>% 
  na.omit() %>% 
  count(Latitude, Longitude) ->
  srdbv4_count

# change count number > 10 to 10, otherwise some circle will be too big
srdbv4_count %>% 
  mutate(n2 = ifelse(n>=10, 10, n)) -> 
  srdbv4_count

sitemap <- basemap +
  geom_point(data = srdbv4_count, aes(x = srdbv4_count$Longitude, y = srdbv4_count$Latitude), 
               color = "black", shape = 1, size = srdbv4_count$n2*0.65, alpha = 0.25)

# add new points from version 5
## added in Chinese
srdb_study %>% select(Study_number, nonEnglish) %>% filter(nonEnglish == "Y") ->
  nonEngStudy
srdbv4 %>% select(Study_number, Country, Latitude, Longitude) %>% 
  filter(Study_number %in% nonEngStudy$Study_number) %>% 
  filter(Country == "China") -> china_papers

china_papers %>% select(Latitude, Longitude) %>% 
  na.omit() %>% 
  count(Latitude, Longitude) %>% 
  mutate(n2 = ifelse(n>=10, 10, n)) ->
  china_papers

## add papers in Russian
srdbv5 %>% select(Latitude, Longitude, Contributor) %>% 
  filter(Contributor %in% c("NK")) %>% 
  count(Latitude, Longitude) %>% 
  mutate(n2 = ifelse(n>=10, 10, n)) -> 
  russian_papers

## add SRDB-v5 points in other language (mainly in English)
srdbv5 %>% select(Latitude, Longitude, Contributor) %>% 
  filter(Contributor %in% c("JJ", "DP", "JM")) %>% 
  count(Latitude, Longitude) %>% 
  mutate(n2 = ifelse(n>=10, 10, n)) -> srdbv5_add

# plot
# prepare data for legend
cc_legend <- tibble(x = rep(-170, 4),
                    y = c(-10, -25, -40, -55),
                    size = 1)

sitemap <- sitemap +
  geom_point(data = srdbv5_add, aes(x = Longitude, y = Latitude), 
             color = "blue", shape = 1, size = srdbv5_add$n2*0.65, alpha = 0.25) +
  geom_point(data = china_papers, aes(x = Longitude, y = Latitude), 
               color = "red", shape = 16, size = china_papers$n2*0.65, alpha = 0.75) +
  geom_point(data = russian_papers, aes(x = Longitude, y = Latitude), 
               color = "orange", shape = 16, size = russian_papers$n2*0.65, alpha = 0.75) +
  # legend
  geom_point(data = cc_legend, aes(x, y, size = size)
             , shape = c(1, 16, 16, 1)
             , color = c("black", "red", "orange", "blue"), alpha = 1) +
  annotate("text", x = -160, y = c(-10, -25, -40, -55)
           , label = c("SRDB-V4", "SRDB-V5 (Chinese)", "SRDB-V5 (Russian)", "SRDB-V5 (other)")
           , size = 3.5, hjust = 0) 

print(sitemap)
# ggsave('outputs/Figure2.srdb_sites.jpg', width = 8, height = 5)
```

## Representative analysis
```{r representative box plot, fig.height=6, fig.width=8}
srdb_v_comp(representative(srdbv1, IGBP, GlobalMATMAP)) -> 
  v1_plot

srdb_v_comp(representative(srdbv2, IGBP, GlobalMATMAP)) -> 
  v2_plot

srdb_v_comp(representative(srdbv3, IGBP, GlobalMATMAP)) -> 
  v3_plot

srdb_v_comp(representative(srdbv4, IGBP, GlobalMATMAP)) -> 
  v4_plot

srdb_v_comp(representative(srdbv5, IGBP, GlobalMATMAP)) -> 
  v5_plot

# use cowplot put them together
plot_grid(v1_plot, v2_plot, v3_plot, v4_plot, v5_plot
          , labels = c("v1", "v2", "v3", "v4")
          , ncol = 2)

```

## Representative analysis - density plot
```{r Figure 3 and 4 - representative density plot, fig.height=8, fig.width=6}
IGBP %>% 
  filter(barren_yn == 0) ->
  IGBP

# prepare data
bind_rows(representative(srdbv1, IGBP, GlobalMATMAP) %>% mutate(vs = "SRDB-V1"),
          representative(srdbv2, IGBP, GlobalMATMAP) %>% mutate(vs = "SRDB-V2"),
          representative(srdbv3, IGBP, GlobalMATMAP) %>% mutate(vs = "SRDB-V3"),
          representative(srdbv4, IGBP, GlobalMATMAP) %>% mutate(vs = "SRDB-V4"),
          representative(srdbv5, IGBP, GlobalMATMAP) %>% mutate(vs = "SRDB-V5")
          ) ->
  srdb_comb

# plot MAT density comparison
srdb_comb %>% 
  filter(vs %in% c('SRDB-V4', 'SRDB-V5')) %>%
  filter(!is.na(Ecosystem) & !is.na(MAT)) %>% 
  filter(Ecosystem2 %!in% c("Arctic", "Desert", "Savanna", "Wetland", "Urban")) %>% 
  ggplot(aes(x = MAT, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem2),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none") +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAT~"("~degree~C~")"), y=expression(Density)) ->
  MAT_rep1

srdb_comb %>% 
  filter(vs %in% c('SRDB-V4', 'SRDB-V5')) %>%
  filter(!is.na(Ecosystem) & !is.na(MAT)) %>% 
  filter(MAT >= -20) %>% 
  filter(Ecosystem2 %in% c("Arctic", "Desert", "Savanna", "Wetland", "Urban")) %>% 
  ggplot(aes(x = MAT, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem2),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none"
        , axis.title.y=element_blank()) +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAT~"("~degree~C~")"), y=expression(Density)) ->
  MAT_rep2

plot_grid(MAT_rep1, MAT_rep2,
          ncol = 2,
          rel_widths = c(1.03, 1))

# ggsave('outputs/Figure3.MAT.jpg', width = 8, height = 6)

# plot MAT density comparison
srdb_comb %>% 
  filter(!is.na(Ecosystem) & !is.na(MAT)) %>% 
  ggplot(aes(x = MAT, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none"
        # , axis.title.x=element_blank()
        , axis.text.x = element_text(angle = 25, hjust = 1)) +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAT~"("~degree~C~")"), y=expression(Density))

# ggsave('outputs/FigureS1.MAT.jpg', width = 8, height = 8)
```



```{r MAP representation analysis}
# plot MAP density comparison
srdb_comb %>% 
  filter(vs %in% c('SRDB-V4', 'SRDB-V5')) %>%
  filter(!is.na(Ecosystem) & !is.na(MAP)) %>% 
  filter(Ecosystem2 %!in% c("Arctic", "Desert", "Shrubland", "Wetland", "Grassland")) %>% 
  filter(MAP <= 5000) %>% 
  ggplot(aes(x = MAP, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem2),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, hjust = 1)) +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAP~"(mm)"), y=expression(Density)) ->
  MAP_rep1

srdb_comb %>% 
  filter(vs %in% c('SRDB-V4', 'SRDB-V5')) %>%
  filter(!is.na(Ecosystem) & !is.na(MAP)) %>% 
  filter(Ecosystem2 %in% c("Arctic", "Desert", "Shrubland", "Wetland", "Grassland")) %>% 
  filter(MAP <= 1000) %>% 
  ggplot(aes(x = MAP, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem2),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1)) +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAP~"(mm)"), y=expression(Density)) ->
  MAP_rep2

plot_grid(MAP_rep1, MAP_rep2,
          ncol = 2,
          rel_widths = c(1.03, 1))

ggsave('outputs/Figure4.MAP.jpg', width = 8, height = 6)

# plot MAP density comparison
srdb_comb %>% 
  filter(!is.na(Ecosystem) & !is.na(MAP) & MAP < 4500) %>% 
  ggplot(aes(x = MAP, fill = factor(Source))) +
    facet_grid(rows = vars(Ecosystem),
               cols = vars(vs),
               scales = "free") +
  theme(legend.position = "none"
        # , axis.title.x=element_blank()
        , axis.text.x = element_text(angle = 25, hjust = 1)) +
  # geom_violin(draw_quantiles = c(0.5))
  geom_density(alpha = 0.5) +
  labs(x=expression(MAP~"(mm)"), y=expression(Density))

# ggsave('outputs/FigureS2.MAP.jpg', width = 8, height = 8)
```



## Test whether add Rs_annual data significantly change the density distribution
```{r, fig.height=6, fig.width=8}

plot_grid(
  # plot annual and growing season Rs
  bind_rows(
  srdbv4 %>% 
    select(Rs_annual, Rs_growingseason) %>%
    rename("(a) Annual" = Rs_annual,
           "(b) Growing season" = Rs_growingseason) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0 & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V4"),
  srdbv5 %>% 
    select(Rs_annual, Rs_growingseason) %>%
    rename("(a) Annual" = Rs_annual,
           "(b) Growing season" = Rs_growingseason) %>%
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0  & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V5")) %>% 
  ggplot(aes(x=Version, y=Rs, fill = Version)) +
  geom_jitter(shape = 16, position = position_jitter(0.2), col = "gray") +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.25) +
    scale_fill_brewer(palette="Accent") +
  facet_grid(rows = vars(Season),
             scales = "free") +
  # geom_density(alpha = 0.35) +
  theme(legend.title = element_blank(),
        legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) +
  labs(y = expression(R[S]~"("~g~C~m^{2}~day^{-1}~or~year^{-1}~")")),
  
  # plot dry and wet season Rs
  bind_rows(
  srdbv4 %>% 
    select(Rs_dry, Rs_wet) %>%
    rename("(c) Dry season" = Rs_dry,
           "(d) Wet season" = Rs_wet) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0 & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V4"),
  srdbv5 %>% 
    select(Rs_dry, Rs_wet) %>%
    rename("(c) Dry season" = Rs_dry,
           "(d) Wet season" = Rs_wet) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0  & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V5")) %>% 
  ggplot(aes(x=Version, y=Rs, fill = Version)) +
  geom_jitter(shape = 16, position = position_jitter(0.2), col = "gray") +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.25) +
    scale_fill_brewer(palette="Accent") +
  facet_grid(rows = vars(Season),
             scales = "free") +
  # geom_density(alpha = 0.35) +
  theme(legend.title = element_blank(),
        legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) +
  labs(y = expression(R[S]~"("~g~C~m^{2}~day^{-1}~")"),
       x = element_blank()),
  
  # plot spring and summer season Rs
  bind_rows(
  srdbv4 %>% 
    select(Rs_spring, Rs_summer) %>%
    rename("(e) Spring" = Rs_spring,
           "(f) Summer" = Rs_summer) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0 & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V4"),
  srdbv5 %>% 
    select(Rs_spring, Rs_summer) %>%
    rename("(e) Spring" = Rs_spring,
           "(f) Summer" = Rs_summer) %>%
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0  & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V5")) %>% 
  ggplot(aes(x=Version, y=Rs, fill = Version)) +
  geom_jitter(shape = 16, position = position_jitter(0.2), col = "gray") +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.25) +
    scale_fill_brewer(palette="Accent") +
  facet_grid(rows = vars(Season),
             scales = "free") +
  # geom_density(alpha = 0.35) +
  theme(legend.title = element_blank(), legend.position = "none") +
  labs(y = expression(R[S]~"("~g~C~m^{2}~day^{-1}~")"),
       x = element_blank()),
  
  # plot autumn and winter season Rs
  bind_rows(
  srdbv4 %>% 
    select(Rs_autumn, Rs_winter) %>%
    rename("(g) Autumn" = Rs_autumn,
           "(h) Winter" = Rs_winter) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0 & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V4"),
  srdbv5 %>% 
    select(Rs_autumn, Rs_winter) %>%
    rename("(g) Autumn" = Rs_autumn,
           "(h) Winter" = Rs_winter) %>% 
    tidyr::gather(key = "Season", value = "Rs") %>% 
    filter(Rs < 5000 & Rs > 0  & !is.na(Rs)) %>% 
    mutate(Version = "SRDB-V5")) %>% 
  ggplot(aes(x=Version, y=Rs, fill = Version)) +
  geom_jitter(shape = 16, position = position_jitter(0.2), col = "gray") +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.25) +
    scale_fill_brewer(palette="Accent") +
  facet_grid(rows = vars(Season),
             scales = "free") +
  # geom_density(alpha = 0.35) +
  theme(legend.title = element_blank(), legend.position = "none") +
  labs(y = expression(R[S]~"("~g~C~m^{2}~day^{-1}~")"),
       x = element_blank()),
  
  ncol = 2,
  rel_heights = c(1, 1.05)
)

# ggsave('outputs/Figure5-Rs.jpg', width = 7, height = 6)
```


## Text for the ESSD paper

```{r}
srdb_study %>% 
  select(nonEnglish) %>% 
  count(nonEnglish)

srdbv5 %>% 
  select(Study_number) %>% 
  unique()

srdbv5 %>% 
  select(Record_number, Study_number) %>% 
  filter(Record_number > 6631) %>% 
  select(Study_number) %>% 
  unique()

srdbv4 %>% 
  select(Rs_growingseason) %>% 
  na.omit()

srdbv5 %>% 
  select(Rs_growingseason) %>% 
  na.omit()

```








